### ISSUE TITLE
2 Akua Issues

### ISSUE THREAD

**Issue by OniNoHanzo** [RavienGaming/Reforged-Eden-2#91] opened 2024-06-02 22:58 UTC
### Reforged Eden 2 Build Number

8

### Game mode

Survival, Single Player

### Tested in vanilla

Issue does not happen in vanilla

### Description of issue

1. Landing both CV/SV's teleport above me after exiting the control seat/cockpit. 
2. PDA Mission to go to Kenex Station 62 - POI's and anything that is supposed to be in the sector are MIA

Followed the recommendations, shutdown, reinstall, still happens for both issues i have in my save

### Error code from console or log (Optional)

1. No errors listed, just happens like that action was meant to happen
2. PDA: Playfield POI 'Kenex Station 62' not found (we'll check again after changing pf)

### POI Name

Kenex Station 62

### Playfield Name

Akua

### Star Name

Alpha

### Mission Name

Among the Stars

### Mission Objective

Reach Kenex station

**Comment by RavienGaming** [comment] 2024-06-02 23:10
The second issue would be a duplicate of one of the issues outlined in issue #16 such as using the changemode command to change your save into creative. Akua uses fixed POI spawns so they will always appear in the same places in survival.
The first issue would be a game bug.

When reproducing a game bug in a vanilla save, make sure you are using the same mode _(singleplayer/co-op/dedicated multiplayer, survival/creative)_ as what you were using when the issue happened in the scenario.
To see a list of known game bugs or to report a new one please see: https://empyriononline.com/forums/bugs.24/

**Closed as completed by RavienGaming** 2024-06-02 23:10 UTC
Labels: game bug
