### ISSUE TITLE
Pirates in Poloris Satellite don't shoot.

### ISSUE THREAD

**Issue by codem1966** [RavienGaming/Reforged-Eden-2#324] opened 2024-09-25 04:04 UTC
### Reforged Eden 2 Build Number

21

### Game mode

Survival, Co-op, Dedicated Server

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

In Chapter 4 : The Cruel Stars,   there is a mission to look at some Polaris satellites.   451 has three pirates.  they don't move or shoot.  just walk up to them and blast them.

### POI Name

Communication Relay 451

### Playfield Name

Akura Space ?

### Playfield Class

space

### Star Name

Alpha

### Mission Name

Chapter 4: The Cruel Starts

### Game Seed

1011345

**Comment by RavienGaming** [comment] 2024-09-25 09:54
Duplicate of #15

**Closed as completed by RavienGaming** 2024-09-25 09:54 UTC
Labels: duplicate

**Comment by codem1966** [comment] 2024-09-25 19:28
are we sure is a duplicate?   This mission is part of the scenario, not part of the vanilla game.
