### ISSUE TITLE
Unable to alter difficulty settings.

### ISSUE THREAD

**Issue by Shadowpheonix** [RavienGaming/Reforged-Eden-2#239] opened 2024-07-21 21:59 UTC
### Reforged Eden 2 Build Number

17

### Game mode

Survival, Single Player

### Tested in vanilla

Issue does not happen in vanilla

### Description of issue

Game difficulty settings during game creation are ignored as are attempts to change them later through the Load Game screen.
Difficulty settings changes are correctly updated in the GAMEOPTIONS.YAML - however, once in game the difficulty settings are always set to...
```DiffEscapePodContent: 	Medium
DiffPlayerBackpackDrop: DropEverything
DiffPlayerProgression: 	Normal
DiffAmountOfOre: 	Normal
DiffNumberOfDeposits: 	Normal
DiffDroneBaseAttack: 	Normal
DiffDronePresence: 	Normal
DiffAttackStrength: 	Medium
DiffConstrCraftTime: 	Normal
DiffBpProdTime: 	Normal
DiffDegradation: 	Normal
DiffRadTemp: 		Normal
DiffFoodConsumption: 	Normal
DiffOxygenConsumption: 	Normal
``` 
This only occurs with games created using Reforged Eden 2 build 17 - existing games that were created in older builds do not have this issue, nor do games created with other scenarios.
I do not know if build 16 had this issue or not, but build 15 definitely did not.

### Error code from console or log (Optional)

No errors reported in the console.

**Comment by RavienGaming** [comment] 2024-07-21 22:04
Duplicate of #19

**Closed as completed** 2024-07-21 22:05 UTC
Labels: duplicate

**Comment by Shadowpheonix** [comment] 2024-07-22 07:10
This is NOT a duplicate of #19 as neither of the workarounds listed function.

> 2 workarounds:
>
>Set your desired difficulty settings, then change the seed, then select your starting planet.
>Start the game using the scenario's default difficulty settings and the starting planet of your choice, quit to main menu, and then on the load game screen change your difficulty settings in there for that save game.

These do not result in modified difficulty settings once in the game.  To confirm, once in the game open the console and run the "difficulties" command.
In addition, if you open the difficulty settings, make changes, OK out, then go right back in you will see your settings were NOT saved.  However, if you go look at the GAMEOPTIONS.YAML for your save, you will see the settings changed there - they just do not take effect once in the game.
I am attaching a Windows Problem Steps Recorder log (viewable with Microsoft Edge or any other browser that supports MHT files) showing me using the "Set your desired difficulty settings, then change the seed, then select your starting planet" steps and still getting the wrong difficulties in game.
[RE2_Difficulty_Bug.zip](https://github.com/user-attachments/files/16329236/RE2_Difficulty_Bug.zip)

FYI, these same steps work perfectly with build 15 (I restored a backup to confirm).

**Comment by Shadowpheonix** [comment] 2024-07-22 07:20
I decided to also do a Windows Problem Steps Recorder log of my attempting to change difficulty settings for existing games created with both build 17 and build 15.
[RE2_Difficulty_Bug_2.zip](https://github.com/user-attachments/files/16329344/RE2_Difficulty_Bug_2.zip)
As you can see, the build 15 settings update easily, but the build 17 settings do not.

**Comment by RavienGaming** [comment] 2024-07-22 07:41
If this is a different game bug then it would need to be reported to Eleon. I'll attach the reporting steps below. There's nothing that can be done to fix this within a scenario sadly.

When reproducing a game bug in a vanilla save, make sure you are using the same mode _(singleplayer/co-op/dedicated multiplayer, survival/creative)_ as what you were using when the issue happened in the scenario.
To see a list of known game bugs or to report a new one please see: https://empyriononline.com/forums/bugs.24/

**Comment by Shadowpheonix** [comment] 2024-07-22 13:20
> If this is a different game bug then it would need to be reported to Eleon. I'll attach the reporting steps below. There's nothing that can be done to fix this within a scenario sadly.
> 
> When reproducing a game bug in a vanilla save, make sure you are using the same mode _(singleplayer/co-op/dedicated multiplayer, survival/creative)_ as what you were using when the issue happened in the scenario. To see a list of known game bugs or to report a new one please see: https://empyriononline.com/forums/bugs.24/

I do not believe this is a game bug.  It does not happen in Vanilla, it does not happen with other scenarios, and it does not happen with earlier builds of Reforged Eden 2.  It occurs ONLY with Reforged Eden 2 Build 17.
