### ISSUE TITLE
Metallic Moons: Impossible to Mine Platinum

### ISSUE THREAD

**Issue by Ipurgepeople** [RavienGaming/Reforged-Eden-2#117] opened 2024-06-10 18:33 UTC
### Reforged Eden 2 Build Number

Build 8

### Game mode

Survival, Single Player

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

I found a metallic moon, and when I attempted to mine up the platinum deposit via the nearby rift, it was not possible to dig beyond the rift biome, and thus the platinum was impossible to reach. I tried via 2 different rifts to no avail.

As stated above, this happened in Build 8, but I suspect it would be the same now in the current update.

### Error code from console or log (Optional)

N/A

### POI Name

Platinum Deposit

### Playfield Name

Cam Moon 1

### Playfield Class

Metallic Moon

### Star Name

Runemi

### Star Class

K4

### Game Seed

964411

**Comment by Mario-Radinovic** [comment] 2024-06-14 09:57
After reading the description of Metalic Moon in game, to me it sounds like it is intended that you use autominer on platinum, not  mine it with your ship. Only gold seems to be reachable (likely because it can't be automined)

**Comment by Nothemal** [comment] 2024-06-29 02:42
The platinum deposits are below the lower playfield edge. They can't be reached even after digging under to the outer crust all the way to them.

**Comment by Garaman-EGS** [comment] 2024-07-13 06:32
Yep, can confirm the platinum deposits are below the "bedrock" lower unminable layer. These deposits probably need to be removed from the planet spec at this point, or their depth adjusted to be reachable through tunneling.
![20240713023240_1](https://github.com/user-attachments/assets/7e1ed670-0b9a-4d1f-b380-b065b2ed211c)

**Comment by RavienGaming** [comment] 2024-07-13 09:27
Yeah it was intended that you use autominers on them but that was a holdover from Project Eden which used the vanilla configs and allowed platinum to be automined.
Should be fixed for next update so you can mine the platinum deposits.

**Closed as completed** 2024-07-18 00:32 UTC
Labels: fixed
