### ISSUE TITLE
Positron Blaster Turret - Reload not working

### ISSUE THREAD

**Issue by dsderfan** [RavienGaming/Reforged-Eden-2#173] opened 2024-06-29 16:11 UTC
### Reforged Eden 2 Build Number

RE2 Build 14

### Game mode

Survival

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

The "Positron Blaster Turret" (BA) (From the Heavy Energy Turret Group) does not recognize its ammunition. If i take controll of it and shot, it will not reload and gives the error, that ammunition is missing. but when i reload manual by pressing "R" it works. it also never reloads while it automatically shots on a target.

**Comment by RavienGaming** [comment] 2024-06-29 19:55
Duplicate of #79 with it not working with ammo.

**Comment by RavienGaming** [comment] 2024-06-29 19:57
However it not reloading automatically while controlled is due to AutoReload: false being set in the block config. Will need Vermillion to check if that's intended or not.

**Comment by VermillionX** [comment] 2024-06-30 00:36
Already changed for the next update.

**Closed as completed** 2024-07-01 05:00 UTC
Labels: fixed
