### ISSUE TITLE
Issue with loading Rogue starts

### ISSUE THREAD

**Issue by BlazingDoctor** [RavienGaming/Reforged-Eden-2#313] opened 2024-09-12 03:30 UTC
### Reforged Eden 2 Build Number

21

### Game mode

Single Player

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

I get an error popup whenever I load into rogue starts when it starts loading structures. When I get into game after dismissing them then I do not get the IDA popup and can't get my items in the armory.
[Client_240911-201253-71.log](https://github.com/user-attachments/files/16972935/Client_240911-201253-71.log)

### Game Seed

726662

**Comment by BlazingDoctor** [comment] 2024-09-12 03:35
I eventually got it to work, I think it may be dependent on seed, got about 3 bad in a row so was worried it may be something else, but I got a working one.

**Comment by RavienGaming** [comment] 2024-09-12 04:19
Did you completely restart your game all the way back to windows desktop in between attempts or anytime you quit a save or disconnected from a server? From the log it looks like you had started a game and then quit to the main menu and tried to start a new game which will cause issues potentially if you didn't fully quit the game in between play sessions.

**Comment by BlazingDoctor** [comment] 2024-09-12 04:21
I did restart my game, even completely reinstalled reforged eden 2 and verified my game files, the issue still persisted afterwards.

**Comment by RavienGaming** [comment] 2024-09-12 04:31
I get a continue or quit error to pop up when changing game seed every time. Probably the same or similar issue to #19 .
Only seems to happen with scenarios that have been uploaded to the workshop, so unsure if it also happens client side on your end but I cannot set a specific seed during game creation for any scenario I uploaded to the workshop but if it's a local copy I used it doesn't trigger.
Possibly will be fixed once the next game update comes out.

Possible work around: don't change the seed, or use a local copy of the scenario if you must set a specific seed. Or wait until next game update to see if it's fixed.
I will mark this as closed as a duplicate, as there's no way for me to fix this issue.

This is likely a game bug and will need to be reproduced and reported using a vanilla save game.
When reproducing a game bug in a vanilla save, make sure you are using the same mode _(singleplayer/co-op/dedicated multiplayer, survival/creative)_ as what you were using when the issue happened in the scenario.
To see a list of known game bugs or to report a new one please see: https://empyriononline.com/forums/bugs.24/

**Closed as completed by RavienGaming** 2024-09-12 04:31 UTC
Labels: game bug
