### ISSUE TITLE
A noob made this scenario

### ISSUE THREAD

**Issue by pantheis** [RavienGaming/Reforged-Eden-2#3] opened 2024-04-29 03:28 UTC
### Important Troubleshooting Information

- [X] I have searched for my issue and read over the troubleshooting thread.

### Reforged Eden 2 Build Number

666

### Is your RE2 build up to date?

Yes, it matches.

### Game mode

- [x] Single Player
- [X] Co-op
- [X] Dedicated Server

### Playfield Name (Optional)

Phobos

### Playfield Class (Optional)

Rocky Moon

### Star Name (Optional)

Sol

### Star Class (Optional)

G2

### Mission Name (Optional)

Project Doom

### What is the issue

The entire moon is filled with screeching demons, and some guy in this weird outfit. Every time he starts fighting them, heavy metal music plays. Seems out of place for Reforged Eden 2.

### Error code from console or log (Optional)

Error 404 - Doomslayer not found.

**Comment by RavienGaming** [comment] 2024-04-29 03:42
The Doom Slayer cannot be stopped and I don't recommend getting in his way to try so this issue won't be fixed sorry.

**Comment by RavienGaming** [comment] 2024-04-29 09:41
Duplicate of #2

**Closed** 2024-04-29 09:41 UTC
Labels: technical
