### ISSUE TITLE
Colonist Turrets replaced by Wind Turbines

### ISSUE THREAD

**Issue by cddrury** [RavienGaming/Reforged-Eden-2#316] opened 2024-09-15 15:46 UTC
### Reforged Eden 2 Build Number

22

### Game mode

Co-op, Dedicated Server

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

I have a carrier that had a number of Colonist Bolter Turrets and Colonist Light Missile Turrets that magically transformed into Wind Turbines.
![BE2-B16_2024-09-15_10-28-27](https://github.com/user-attachments/assets/88d61ba9-c9df-483e-942f-3bf258a2fae4)

### Error code from console or log (Optional)

No error message.

### Playfield Name

Delta UCHN Odyssey

### Playfield Class

UCHN Odyssey space

### Star Name

Delta

### Star Class

FStartingSystem

**Comment by cddrury** [comment] 2024-09-15 16:16
It also replaced something (I haven't determined what) on my Rich Asteroid Miner. Whatever it replaced, it also deleted my eight Rich Asteroid Drills.

![BE2-B16_2024-09-15_11-12-34](https://github.com/user-attachments/assets/25d0afd2-633c-4123-b5b9-3cfb55553b2d)

**Comment by RavienGaming** [comment] 2024-09-15 21:23
Duplicate of #10

**Closed as completed by RavienGaming** 2024-09-15 21:23 UTC
Labels: duplicate
