### ISSUE TITLE
Still cannot upgrade SV shield gen. 

### ISSUE THREAD

**Issue by PoorLuckPierre** [RavienGaming/Reforged-Eden-2#171] opened 2024-06-28 02:57 UTC
### Reforged Eden 2 Build Number

14

### Game mode

Creative

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

SV basic shield generator can still not be upgraded with the multi tool. A previous ticket was closed in May that mentioned SV shields and turrets with a mentioned fix on the way. However SV shield generators currently still can't be upgraded. The game says no upgrade exists or must be unlocked in the tech tree.

**Comment by RavienGaming** [comment] 2024-06-28 04:00
Duplicate of #21 
See that issue for an explanation for why this happens.

**Closed as completed by RavienGaming** 2024-06-28 04:00 UTC
Labels: duplicate
