### ISSUE TITLE
getting mass spam pop up for "a problem accured" I hit continue and it immediately pops back up.

### ISSUE THREAD

**Issue by Keoke-san** [RavienGaming/Reforged-Eden-2#152] opened 2024-06-21 02:40 UTC
### Reforged Eden 2 Build Number

Build 13

### Game mode

Single Player

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

I didn't have this issue until after the EGS update and RE2 build 12 update. On single player, after EGS launched their update, and then RE2 was updated, I created a new save game, I didn't want to deal with any problems from my old scenario not being fully updated. I put in the commands to get back to where I was at in the first playthrough. While on Akua, I went to take out a Zirax com relay POI and as I am inside I start getting the spam for "a problem has accured" Continue, continue and mail or exit and mail. Either of the continue options it just starts spamming me. I can't even get my mouse to hit continue, hit escape, and get to the exit game before it pops up again.

I got on the workshop, read the troubleshooting tips, nothing worked. So I said whatever, I'll just create a new game and get myself caught up again. 

Everything worked fine. I took out some Zirax POIs even a com relay, no problems. Left planet Akua, went to a couple Polaris space stations, went to UCH, flew to Akua Moon 1, took out a zirax vehicle bay, went to take out another zirax POI (Can't remember the name of it), and while I am in my SV taking out the 2nd turret, I start getting spammed with the message again. So I went back to the troubleshooting on the workshop, tried it all again, and nothing works. I am going to have to restart my game AGAIN. :( Please help.

**Comment by Keoke-san** [comment] 2024-06-21 02:43
![image](https://github.com/RavienGaming/Reforged-Eden-2/assets/172148997/1e7e12e8-c78b-4a87-b432-42d36eb66a69)

**Comment by RavienGaming** [comment] 2024-06-21 03:03
What does the log show for the error message?
Did you have the debug menu open when this happened (console command: di).
What specific console commands did you use as those could be the reason why.

**Comment by Keoke-san** [comment] 2024-06-21 03:07
I've only ever used console commands "im" "SBP" "GM" and "TT" 
Also, I just logged off of the new game that I started, and logged over to the corrupted one to see if I could manage to get to the console command and type di, and I am no longer getting the error message at the moment. 
But, this is the first time that I haven't gotten the error after relogging. Not sure if creating the new game file and loading into that one has anything to do with it or not though.

**Comment by Keoke-san** [comment] 2024-06-21 03:08
edit: I didn't have any console commands going when I was fighting the POI. I only used those commands to get me caught back up to where I was when I created the new game file.

**Comment by RavienGaming** [comment] 2024-06-21 03:42
And just making sure you're completely restarting the game back to windows desktop whenever you load a different save?
I'll leave this open for a few days in case you get the error spam again, but it's probably a game bug.

**Comment by Keoke-san** [comment] 2024-06-21 03:48
Yes I did go exit out back to desktop. I will say the only thing that is bugging out about it now is this is spamming in the command thing. I noticed it when i went to turn on di so i can just have it on all the time in case it happens again. 
![image](https://github.com/RavienGaming/Reforged-Eden-2/assets/172148997/245f6486-c541-4bb4-ad8c-7d6d4195af1a)

**Comment by RavienGaming** [comment] 2024-06-21 06:40
Same error as #149 . Obvious question did you have a deconstructor on your ship? Was it working on anything?
I already checked the deconstructor and it caused no errors for me, normally if it's a scenario configuration problem the deconstructor will literally delete parts of your ship or throw an error right away when opening it. The fact that this is only happening some of the time is very odd and makes it hard to track down the problem.

I will try to look into a couple things it could be, but this may also be a new game bug introduced in the latest update which would require testing in a vanilla save.


When reproducing a game bug in a vanilla save, make sure you are using the same mode _(singleplayer/co-op/dedicated multiplayer, survival/creative)_ as what you were using when the issue happened in the scenario.
To see a list of known game bugs or to report a new one please see: https://empyriononline.com/forums/bugs.24/

**Comment by RavienGaming** [comment] 2024-06-21 07:04
I just tried blowing up every Zirax POI on the Alpha I Moon playfield and couldn't get the error to happen.

**Comment by Keoke-san** [comment] 2024-06-21 08:45
Thanks! I have been playing on that same save for a while now and no issues again. I do have a deconstructor on my ship, but it's powered off and I haven't used it in a couple of days. I appreciate your work on this, I am sorry I couldn't be more helpful. Next time I'll be sure to do the debug thing, I didn't know that was a thing until you mentioned it here. 

If I could figure out the cause and make it happen whenever I wanted, i would definitely see if i could recreate it on vanilla. but I don't really want to do a vanilla playthrough just to HOPE that I get the bug haha. 

I'm loving RE2 though, you and Vermillion are pretty awesome. If it happens again I'll definitely let you know though.

**Comment by RavienGaming** [comment] 2024-06-21 18:08
The di command was more that if you have a ship with negative shields, it will cause an error spam loop when you look at it with di active. So you don't need to worry about using that command, I was just trying to rule that specific bug out as an issue.

I'll go ahead and keep this issue open in case anyone else has the same problem, but this very well could be a new game bug.

**Comment by RavienGaming** [comment] 2024-07-01 05:01
I will go ahead and close this issue as no one else has reported the same thing happening.
If it happens again please feel free to open a new issue, but this is still likely to be a game bug not a scenario bug.

**Closed as completed by RavienGaming** 2024-07-01 05:01 UTC
Labels: more info needed
