### ISSUE TITLE
Completion of Polaris Mining Foreman unlock quest does not result in +Polaris reputation

### ISSUE THREAD

**Issue by StHotPants** [RavienGaming/Reforged-Eden-2#73] opened 2024-05-26 18:38 UTC
### Reforged Eden 2 Build Number

RE2 Build 7

### Game mode

Survival

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

Found a Polaris Mining Foreman vessel in a Polaris Asteroid sector. Foreman unlock quest was to provide him with a Basic Autominer which he paid 79k credits for (above market value) and an unused Mining Contract. However, when handing in the Basic Autominer there was no + Polaris reputation given. I believe the quest completion should result in a basic amount of +Polaris reputation (recommendation: 500 reputation)

### POI Name

Polaris Mining Foreman

### Playfield Name

EZIO 22375 II

### Playfield Class

Asteroid Field

### Star Name

Alasuma

### Star Class

D

### Mission Objective

Return to Mining Foreman with 1 Basic Autominer

### Game Seed

25781

**Comment by RavienGaming** [comment] 2024-05-26 18:53
Duplicate of #74

**Closed as completed by RavienGaming** 2024-05-26 18:53 UTC
Labels: duplicate
