### ISSUE TITLE
Missing Relays on Chapter 4 last mission

### ISSUE THREAD

**Issue by JaegerLeo** [RavienGaming/Reforged-Eden-2#403] opened 2024-12-18 21:50 UTC
### Reforged Eden 2 Build Number

Build 25

### Game mode

Survival

### Tested in vanilla

Reproduced in vanilla

### Description of issue

![Empyrion - Galactic Survival Screenshot 2024 12 18 - 15 04 30 69](https://github.com/user-attachments/assets/7721733e-4659-46ed-9fde-6166165d8eb3)
![Empyrion - Galactic Survival Screenshot 2024 12 18 - 15 10 11 62 - Copy](https://github.com/user-attachments/assets/9efc6495-3938-4862-8460-1c9657d05306)
![Empyrion - Galactic Survival Screenshot 2024 12 18 - 15 12 09 68](https://github.com/user-attachments/assets/794a9607-1476-4b18-8e07-80743a22fcd8)
![Empyrion - Galactic Survival Screenshot 2024 12 18 - 15 31 59 04](https://github.com/user-attachments/assets/1680d7b2-88c3-42f5-9edb-dcb231d417af)

When trying to reach relay satellite for last mission of chapter 4, the relay sat is missing.

**Comment by RavienGaming** [comment] 2024-12-18 23:04
One last ditch effort to try to figure out how this happened.

Can you go into your saves folder (under Empyrion - Galactic Survival/Saves/Games/YourSaveGame.

Under the folder for your save game should be a Templates folder.
Under that is a folder for Akua Sector with a playfield.yaml file.
Can you upload the playfield.yaml file here? Should be able to drag and drop like the screenshots.

This is likely a game bug or something that went wrong when you installed the scenario from Nexus Mods somehow.
I tried to reproduce this with the same seed but I get all the proper POIs like so:

![20241218145953_1](https://github.com/user-attachments/assets/f00c6d15-b64f-428e-892b-56b6f4ad515c)

**Comment by RavienGaming** [comment] 2024-12-18 23:06
Also did you, at any time during this save game, either use the cm or changemode console commands, and/or reload the save orf a different save/server without fully quitting the game back to windows desktop?

**Comment by JaegerLeo** [comment] 2024-12-18 23:07
> Also did you, at any time during this save game, either use the cm or changemode console commands, and/or reload the save orf a different save/server without fully quitting the game back to windows desktop?

I may have, but I can't recall, I noticed the warning a bit late into the run, also it says I can't upload that file type here.

**Comment by RavienGaming** [comment] 2024-12-18 23:11
> > Also did you, at any time during this save game, either use the cm or changemode console commands, and/or reload the save orf a different save/server without fully quitting the game back to windows desktop?
> 
> I may have, but I can't recall, I noticed the warning a bit late into the run, also it says I can't upload that file type here.


Hmm try renaming it to playfield.txt maybe? Of course copy it somewhere else first before renaming it so you don't mess up your save game. And yeah if you had used the changemode command that will corrupt the save unfortunately. If you had used that command that is probably what caused the issue.

**Comment by JaegerLeo** [comment] 2024-12-18 23:13
> > > Also did you, at any time during this save game, either use the cm or changemode console commands, and/or reload the save orf a different save/server without fully quitting the game back to windows desktop?
> > 
> > 
> > I may have, but I can't recall, I noticed the warning a bit late into the run, also it says I can't upload that file type here.
> 
> Hmm try renaming it to playfield.txt maybe? Of course copy it somewhere else first before renaming it so you don't mess up your save game. And yeah if you had used the changemode command that will corrupt
 the save unfortunately. If you had used that command that is probably what caused the issue.

Sorry I meant the save switching, I don'tknow what the changemode command does. Below  attached the file.

[playfield.txt](https://github.com/user-attachments/files/18189819/playfield.txt)

**Comment by RavienGaming** [comment] 2024-12-18 23:19
Switching saves could have done it as well.

cm, or changemode, converts your game into creative or vice versa, but then it really messes things up especially POI spawning.

I can't reproduce this sorry, even your playfield file is the exact same as my own. Only thing I can think of is a game bug (possibly with the Epic version of the game?), changing saves without fully quitting caused issues, or the scenario wasn't downloaded correctly or something.

I will go ahead and close this but please feel free to add on more info if you find out anything new. I'd recommend just making a new save game, perhaps after downloading the scenario again to make sure it's working properly.
Or you can just ignore the mission. Sorry I couldn't help out more.

**Closed as completed by RavienGaming** 2024-12-18 23:19 UTC
Labels: cannot reproduce
