### ISSUE TITLE
Cant start a new single player game

### ISSUE THREAD

**Issue by Cookiepuncher** [RavienGaming/Reforged-Eden-2#335] opened 2024-10-04 07:37 UTC
### Reforged Eden 2 Build Number

1.11.8.4531

### Game mode

Survival

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

I can load a save just fine. I can also play on line servers with no issues. But when I try to start a new single player game, it loads to 98% then goes to the blue planet screen and sits there. I am trying to do custom settings. I have even tried several different setting changes and it did not help. I tried unsubscribing and resubscribing and also verifying my files. none of this helped.

**Comment by RavienGaming** [comment] 2024-10-04 19:46
Duplicate of #19

**Closed as completed by RavienGaming** 2024-10-04 19:46 UTC
Labels: duplicate

**Comment by Cookiepuncher** [comment] 2024-10-04 21:25
It's not a duplicate. Because it also happened if I did not change the
settings.

**Comment by RavienGaming** [comment] 2024-10-05 01:45
Restart your game completely back to desktop, then start a new game and don't change the difficulty settings at all. It should work then. It's the same issue as #19 .
