### ISSUE TITLE
R type systems missing or re-coded. Cannot complete UCH exploration missions.

### ISSUE THREAD

**Issue by BallisticSix** [RavienGaming/Reforged-Eden-2#175] opened 2024-06-29 21:05 UTC
### Reforged Eden 2 Build Number

14

### Game mode

Survival, Dedicated Server

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

Tested on single player and dedicated server. If you search for "R" type system in galaxy map, the only system that appears is the Dyson Core system. I have not gone to Progenitor space yet, so I'm not sure if this is intended or not (to have to go to Dyson to complete), but this has not been the case in the previous RE1 scenario, so I'm pretty sure it's a bug. I have also noticed that there are "R-Drone" and "T-Drone" systems now, but they do not appear when searched in the galaxy map either. I went to an R-Drone system and it did not progress the mission.

### POI Name

N/A

### Playfield Name

Galaxy wide

### Playfield Class

N/A

### Star Name

N/A

### Star Class

R

### Mission Name

UCH Survey Galaxy - Exotic Systems

### Mission Objective

Warp to R class system

**Comment by RavienGaming** [comment] 2024-06-29 21:20
Duplicate of #130

**Closed as completed by RavienGaming** 2024-06-29 21:20 UTC
Labels: duplicate
