### ISSUE TITLE
Zirax AI is often inactive and does not respond

### ISSUE THREAD

**Issue by Daimonicon** [RavienGaming/Reforged-Eden-2#321] opened 2024-09-24 08:28 UTC
### Reforged Eden 2 Build Number

Build 22 (09/12/2024)

### Game mode

Single Player

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

You enter a POI and the enemies sometimes don't react at all, as if they don't see the player. Usually occurs in less expansive areas. The whole thing occurs in various POI's on several visited planets. Never observed on the Legacy side so far. Location or POI details below are the last occurrence of the error.

### POI Name

Black Cult Temple of Rebirth

### Playfield Name

YSCU 11349 II

### Playfield Class

Alien

### Star Name

Pimumu

**Comment by Daimonicon** [comment] 2024-09-24 09:10
I had forgotten the video. I had already shot the guy when I had the idea to record it. He's definitely still alive and he's not an isolated case - but I've not had it this close so far that they ignore me at a greater distance.

[Video](https://youtu.be/NVd3B9kElko)

**Comment by RavienGaming** [comment] 2024-09-24 18:39
Duplicate of #15

**Closed as completed by RavienGaming** 2024-09-24 18:39 UTC
Labels: duplicate
