### ISSUE TITLE
Schematic for Heavy Railgun turned in, but did not unlock

### ISSUE THREAD

**Issue by Gavodir** [RavienGaming/Reforged-Eden-2#121] opened 2024-06-11 14:12 UTC
### Reforged Eden 2 Build Number

247482

### Game mode

Dedicated Server

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

I brought 2 encrypted schematics to a UCH vessel in a starter system. Decrypted both, got prototype railgun lx-2 and heavy railgun turret. Turned in the prototype schematic and clicked through all the other categories looking for the heavy railgun. Remembered I need to unlock the previous railgun turret first so I did that, then went back into the schematic computer and submitted the heavy railgun turret blueprint. It consumed the item, I'm not completely sure if it consumed 100 UP but I think it did, however the heavy railgun turret is still locked in the tech tree and in constructors.  I'm not actually sure if the prototype railgun unlocked properly as I'm not sure which constructor is needed to make it but I didn't find it in my adv constructor.  This is as much as I can describe at this point as I haven't found new schematics yet.

### POI Name

UCH Vessel

### Playfield Name

UCHN Discovery

**Comment by RavienGaming** [comment] 2024-06-11 16:30
This has been occasionally reported. No idea what the cause of it is but it would be a game bug.
You (or a server admin) can give yourself a new schematic with console command: **give item Token 6407**
For the prototype LX-2 railgun the token ID is 6411.

This issue would need to be reproduced using a DLC game as they use the same unlock functionality in there and then reported on the forums.
When reproducing a game bug in a DLC save, make sure you are using the same mode _(singleplayer/co-op/dedicated multiplayer, survival/creative)_ as what you were using when the issue happened in the scenario.
To see a list of known game bugs or to report a new one please see: https://empyriononline.com/forums/bugs.24/

**Comment by Kainne00** [comment] 2024-06-13 06:43
This recently happened to me, also with the Heavy Railgun.  Research computer ate the schematic and 100 UP.  The heavy railgun is locked (even after a full restart of client) in the uni con, and the BA and CV tech trees.  medium railgun is  and was unlocked prior.

The console gave this error when it ate my schematic:

![image](https://github.com/RavienGaming/Reforged-Eden-2/assets/168397912/2a8a4e62-8589-4cca-9421-4c1d2a5af67a)

**Comment by RavienGaming** [comment] 2024-06-13 22:38
Thank you! This along with a similar issue with the spinal railgun should be fixed for next update. You should be able to use a schematic to unlock it again, no new save game needed once the update drops.

**Closed as completed** 2024-06-14 23:12 UTC
Labels: fixed
