### ISSUE TITLE
EPH_R2PirateAuxT2.epb spawns full of dirt (Needs 'terrain removal' checked)

### ISSUE THREAD

**Issue by jameswsturgeon** [RavienGaming/Reforged-Eden-2#334] opened 2024-10-03 12:26 UTC
### Reforged Eden 2 Build Number

22

### Game mode

Survival

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

EPH_R2PirateAuxT2.epb does not have 'terrain removal' checked in it's properties, so therefore the basement spawns full of dirt.

**Comment by RavienGaming** [comment] 2024-10-03 20:29
Duplicate of #134

**Closed as completed by RavienGaming** 2024-10-03 20:29 UTC
Labels: duplicate
