### ISSUE TITLE
Matter Trasceiver not upgradeable by multitool

### ISSUE THREAD

**Issue by danielsolaro** [RavienGaming/Reforged-Eden-2#94] opened 2024-06-03 03:24 UTC
### Reforged Eden 2 Build Number

8

### Game mode

Survival, Dedicated Server

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

Unlocked upgrade, can only craft it from scratch, not update the current transceiver block
![20240603002257_1](https://github.com/RavienGaming/Reforged-Eden-2/assets/8516353/40b8b3f1-5bdc-4ce5-b631-5317c4cac137)

**Comment by RavienGaming** [comment] 2024-06-03 04:11
Do you already have the maximum number of wireless transmitters? If so then this is a duplicate of #21 .

**Comment by danielsolaro** [comment] 2024-06-03 04:44
No, I have two (one t1 and one t2)
________________________________

**Comment by danielsolaro** [comment] 2024-06-03 04:45
In fact T2 doesn't show the possibility of upgrading either, tho I don't have the materials for t3. But its unlocked.
________________________________

**Comment by VermillionX** [comment] 2024-06-03 10:38
Oh right. They're not upgradable with the multitool at the moment.
Fixed for next update. And i'll need to add new icons to identify the T2 and T3.

**Closed as completed** 2024-06-05 00:00 UTC
Labels: fixed
