### ISSUE TITLE
Ship weapon in the toolbar (selected) and when I get shot an error window opens

### ISSUE THREAD

**Issue by Duke-Engi** [RavienGaming/Reforged-Eden-2#349] opened 2024-10-16 00:17 UTC
### Reforged Eden 2 Build Number

4541

### Game mode

Dedicated Server

### Tested in vanilla

Issue does not happen in vanilla

### Description of issue

When I paste a crafted ship weapon into my toolbar and select it, an error window appears and I cannot click it to continue. The window opens again immediately. (continue, continue and emal, end and email)
When I get shot at by a drone, a base, or whatever, the error window pops up. I can click “Continue” – if I’m quick enough and don’t get shot down right away. If the fire continues, the same window appears again...

### Playfield Name

Akua

**Comment by RavienGaming** [comment] 2024-10-16 01:09
Duplicate of #8

**Closed as completed by RavienGaming** 2024-10-16 01:09 UTC
Labels: duplicate
