### ISSUE TITLE
Creative game won't start

### ISSUE THREAD

**Issue by LokitheDevious** [RavienGaming/Reforged-Eden-2#288] opened 2024-08-31 08:29 UTC
### Reforged Eden 2 Build Number

Don't know, it's the current version I just downloaded tonight

### Game mode

Creative, Single Player

### Tested in vanilla

Issue does not happen in vanilla

### Description of issue

When I try to start a creative game it starts loading, goes to 100% of planets loaded, then goes to the blue main game load screen and hangs up forever (at least, for 4-5 hours the longest time before I stopped the program). I can start and play a survival game in RE2 Beta, or a creative game in RE1 or vanilla, but not a creative game in RE2 Beta. I have restarted my computer and validated my game files and unsubbed and resubbed to the RE2 Beta scenario in the workshop and still have the same issue, again ONLY for creative games in RE2 Beta. I have tried at least 5 times with different game names and on 2 different starter planets without success.

### Error code from console or log (Optional)

None

### Game Seed

None

**Comment by RavienGaming** [comment] 2024-08-31 08:35
What exact steps do you do?
All you should do is exactly the following:

1. Select the Reforged Eden 2 Beta scenario.
2. Click on Game Mode to change the mode to Creative.
3. Click the Start button to start the game.

If you change any other settings it may not work due to a game bug.

**Comment by LokitheDevious** [comment] 2024-08-31 08:45
That worked, thanks. I had been changing the game name.

Perhaps add a sticky announcement in the workshop discussion saying you can't change any of the settings including the name?

**Comment by RavienGaming** [comment] 2024-08-31 20:48
Duplicate of #19

**Closed as completed by RavienGaming** 2024-08-31 20:48 UTC
Labels: game bug
