### ISSUE TITLE
Gyro Jet Attachment (weapon attachment) does not install on Guided Rocket Launcher

### ISSUE THREAD

**Issue by StHotPants** [RavienGaming/Reforged-Eden-2#188] opened 2024-07-04 21:34 UTC
### Reforged Eden 2 Build Number

RE2 Beta Build 14

### Game mode

Dedicated Server

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

The Gyro Jet Attachment is unable to be installed on the player crafted Guided Rocket Launcher.

![image](https://github.com/RavienGaming/Reforged-Eden-2/assets/169509491/29cdb617-e83a-4db1-9c7a-19846f8c7e75)

![image](https://github.com/RavienGaming/Reforged-Eden-2/assets/169509491/70ef4f64-ce0c-4a31-a592-504b3f0f33c5)

**Comment by VermillionX** [comment] 2024-07-05 00:02
Do you mean that it doesn't appear on the list of weapon mods, or that it doesn't change the stats after being applied?

**Comment by StHotPants** [comment] 2024-07-05 00:12
> Do you mean that it doesn't appear on the list of weapon mods, or that it doesn't change the stats after being applied?

It doesn't appear on the list of weapon mods

**Comment by LostInEarth** [comment] 2024-07-05 09:40
isnt this for the ammo not the weapon?

**Comment by VermillionX** [comment] 2024-07-05 10:43
Yes, this is an ammo mod.

**Comment by VermillionX** [comment] 2024-07-18 15:39
So, i'm gonna close this. Since it's apparently not a bug.

**Closed as completed by VermillionX** 2024-07-18 15:39 UTC
Labels: intended
