### ISSUE TITLE
Advanced Wind Turbines

### ISSUE THREAD

**Issue by Borumber** [RavienGaming/Reforged-Eden-2#165] opened 2024-06-25 05:01 UTC
### Reforged Eden 2 Build Number

13

### Game mode

Survival, Dedicated Server

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

I got the recipie for the advanced wind turbines unlocked it at UCH it shows unlocked but the turbines wont upgrade with my multitool as the tooltip suggests. just says no upgrade available.

**Comment by RavienGaming** [comment] 2024-06-25 05:03
How many total wind turbines do you have (how many normal, how many advanced)?

**Comment by Borumber** [comment] 2024-06-25 05:04
16 normal

**Comment by Borumber** [comment] 2024-06-25 05:06
removed a turbine and now it works I misunderstood the tooltip

**Comment by RavienGaming** [comment] 2024-06-25 05:13
Yup duplicate of #24

**Comment by RavienGaming** [comment] 2024-06-25 05:15
Duplicate of #21 . Game doesn't let you upgrade all 16 since it thinks you're trying to add a new one which would put you over the limit. It's not smart enough to know upgrading doesn't actually increase the number of them.

**Closed as completed by RavienGaming** 2024-06-25 05:15 UTC
Labels: duplicate
