### ISSUE TITLE
Empyrion blue splash screen after RE2 attempts to load into scenario

### ISSUE THREAD

**Issue by MaabussCalos** [RavienGaming/Reforged-Eden-2#410] opened 2024-12-30 02:46 UTC
### Reforged Eden 2 Build Number

26

### Game mode

Survival

### Tested in vanilla

Issue does not happen in vanilla

### Description of issue

Every time I try to launch a new game in RE2, it will go to the loading screen, then seem to fail and just gets a blue splash screen.  
![RE2](https://github.com/user-attachments/assets/fe9fac39-81a6-475f-8b7b-01db316e25e0)

### Error code from console or log (Optional)

30-02:33:06.951 19_33 -ERR- Exception while reading playfield configuration file 
F:\SteamLibrary\steamapps\workshop\content\383120\3143225812/Playfields/Atlon/playfield_debug.yaml

### Game Seed

399158

**Comment by RavienGaming** [comment] 2024-12-30 16:39
Duplicate of #19

**Closed as completed by RavienGaming** 2024-12-30 16:39 UTC
Labels: duplicate
