### ISSUE TITLE
NLP Work Order  not working

### ISSUE THREAD

**Issue by TheycallmeBuddy** [RavienGaming/Reforged-Eden-2#206] opened 2024-07-11 21:21 UTC
### Reforged Eden 2 Build Number

NA

### Game mode

Single Player

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

NLP work order doesn't work. Bought it, went to NLP, talked to the merchant and no dialogue option or any option for said work order.

### POI Name

Non Linear Productions

### Playfield Name

OIODD III

### Playfield Class

Temperate Plateau

### Star Name

Mephotryu

### Star Class

G

### Mission Name

Work Order so no name?

### Mission Objective

Work order o.O

### Game Seed

God only knows

**Comment by RavienGaming** [comment] 2024-07-11 22:44
Was the work order in your personal inventory when you talked to the NPC?

**Comment by TheycallmeBuddy** [comment] 2024-07-11 22:58
Yes

**Comment by TheycallmeBuddy** [comment] 2024-07-11 23:23
I don't have to be in Polaris faction space right? Can be in neutral? The NLP station was literally right next to the trade station

**Comment by VermillionX** [comment] 2024-07-12 01:16
I'm not seeing any problem in the dialog. Everything should be working fine (unlike VitaLife, which _is_ bugged).
Are you sure it's NLP you're at and not VitaLife? And that you've got the right work order for the right factory?

**Comment by TheycallmeBuddy** [comment] 2024-07-12 10:59
I'll check another one when I come across it but I checked everything over and over and over 100 times. I opened up the NLP trade guy buy giving him his wanted items because I happened to have em on me. Then I stopped by the trade station which was literally next door to NLP and went to the work order thing to check it out because I've never done one before and seen that there was one for NLP for 60k so I bought it because....well....right next door hah. So put it in my inventory, went back to NLP next door and the merchant guy there had no other dialogue. Like I said, I'll check another one when I come across one

**Comment by Bonedog-DHB** [comment] 2024-07-12 16:15
The only way I've been able to see what game seed I am using is to copy the save file. It inputs the seed in the name of the copy. Is there another way to get the seed number?

**Comment by RavienGaming** [comment] 2024-07-12 18:20
> The only way I've been able to see what game seed I am using is to copy the save file. It inputs the seed in the name of the copy. Is there another way to get the seed number?

Use console command **stats** and it should spit out the game seed, though it's not really needed for this report.

**Comment by TheycallmeBuddy** [comment] 2024-07-12 22:00
So found another NLP and went to talk to the merchant. He asked for 400 energy regulators. Went back to ship and made them, returned to him to turn it in and the order popped up at that moment. He took the order and his inventory became accessible (purchasing/selling). So I'm guessing if you have the merchant already unlocked (for NLP anyway) then the work order doesn't work?

**Comment by RavienGaming** [comment] 2024-07-12 23:04
> So found another NLP and went to talk to the merchant. He asked for 400 energy regulators. Went back to ship and made them, returned to him to turn it in and the order popped up at that moment. He took the order and his inventory became accessible (purchasing/selling). So I'm guessing if you have the merchant already unlocked (for NLP anyway) then the work order doesn't work?

The work order is for completing the job to unlock the trader, so you are correct. It's for when you don't have the resources needed to complete the job.

Should I close this ticket as working as intended?

**Comment by TheycallmeBuddy** [comment] 2024-07-12 23:31
Oh I did not know that. I was thinking it was something else. Yes, sorry to waste time ><

**Comment by RavienGaming** [comment] 2024-07-13 02:49
Thanks for reporting it just in case though!

**Closed as completed by RavienGaming** 2024-07-13 02:49 UTC
Labels: other
