### ISSUE TITLE
Some starter planet choices cause game hang on creation if difficulty adjusted

### ISSUE THREAD

**Issue by Ironbuket** [RavienGaming/Reforged-Eden-2#309] opened 2024-09-09 03:44 UTC
### Reforged Eden 2 Build Number

21

### Game mode

Survival, Single Player

### Tested in vanilla

Issue does not happen in vanilla

### Description of issue

This info is related to the following existing Issue reports and may help with solving/avoiding it

19, 102, 239 and 288 relating to game freezing before reaching planet fall in single player when difficulty settings are adjusted during creation of a new game

Single player, Set game name, Change difficulty, touch nothing else, enter game = hangs.

I believe this is caused by the choice of starter planet. If you do or don’t choose a starter planet before touching difficulty, the game will change your planet choice to Atlon (same every time). The choice of Atlon seems to be the issue. This may well be the vanilla bug which Revien implies (in some github posts) is present and they cant do anything about (the automatic planet change when you adjust difficulty settings). This also might mean that in future Vanilla updates the planet name or behaviour could change again

I tried a few of the other planet choices and other ones hang the game too. But if you select a starting planet which has text descriptions below the RE2 image (center of screen) then loading should work OK.

ie, you scroll through the planet choices, past Atlon, Itaka, Korro, Mato, Taldor until you start seeing planets with coloured text descriptions below the RE2 image (center screen). Choose one of those and the game will load OK and the difficulties in-game seem to stick (as confirmed with difficulties command).

NB: Atlon, Itaka, Korro, Mato, Taldor do not appear as planet choices if you do not change the difficulty. Changing difficulty makes additional planet choices appear for the scenario.

The suggestion by some to regenerate seed, also works as a fix, but only because regenerating the seed changes the starter planet back to one of the working planet choices. The starter planet is the issue.

I think it would be worth this info being posted as a warning somewhere prominent (the scenario description maybe?). Obviously, a shorter version, like ‘If you change single player game difficulty, please make sure to choose one of the following starter planets X, Y, Z and avoid using Atlon, Itaka, Korro, Mato, Taldor)’

**Comment by RavienGaming** [comment] 2024-09-09 03:52
Duplicate of #19

**Closed as completed by RavienGaming** 2024-09-09 03:52 UTC
Labels: duplicate
