### ISSUE TITLE
CV Standard Shield not upgradeable to Advanced Shield

### ISSUE THREAD

**Issue by danielsolaro** [RavienGaming/Reforged-Eden-2#93] opened 2024-06-03 03:22 UTC
### Reforged Eden 2 Build Number

8

### Game mode

Survival, Dedicated Server

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

Upgrades unlocked in the tree, still doesn't show when multitool is in hands.
![20240603002124_1](https://github.com/RavienGaming/Reforged-Eden-2/assets/8516353/cde5c493-0339-49cb-a626-27a835b0fa96)

**Comment by RavienGaming** [comment] 2024-06-03 04:11
Duplicate of #21

**Closed as completed by RavienGaming** 2024-06-03 04:11 UTC
Labels: duplicate
