### ISSUE TITLE
Micro Jump causes OPVs to disappear

### ISSUE THREAD

**Issue by asdf599** [RavienGaming/Reforged-Eden-2#268] opened 2024-08-12 17:27 UTC
### Reforged Eden 2 Build Number

19

### Game mode

Survival, Single Player

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

Using the Micro Jump Drive sometimes causes OPVs in the sector to de-spawn.

Upon further investigation, clicking the "Change jump distance" button is what causes the de-spawn. You do not have to actually perform the jump, or even enter a number in the field. Simply clicking "change jump distance" does it.

Jumping without changing distance does NOT cause de-spawning. So if all else fails, a fixed jump distance would be a solution.

### Error code from console or log (Optional)

AI Space Vessel doesn't exist : Id = 14922 | Type = R2OPVZiraxT2 | Action = ManagerSpaceVessel. AI task has been removed.

**Comment by asdf599** [comment] 2024-08-12 17:37
Upon further investigation, clicking the "Change jump distance" button is what causes the de-spawn. You do not have to actually perform the jump, or even enter a number in the field. Simply clicking "change jump distance" does it.

**Comment by RavienGaming** [comment] 2024-08-13 01:08
Duplicate of #15

**Closed as completed by RavienGaming** 2024-08-13 01:08 UTC
Labels: duplicate
