### ISSUE TITLE
Game Crashing at the almost end of Communication Array mission

### ISSUE THREAD

**Issue by selimozkan** [RavienGaming/Reforged-Eden-2#149] opened 2024-06-20 07:48 UTC
### Reforged Eden 2 Build Number

4480

### Game mode

Survival, Single Player

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

At the almost end of the mission when I arrive to Server room the game crashes unrecoverably.

### Error code from console or log (Optional)

20-06:23:13.347 09_23 -ERR- Exception on playfield 'Omicron Moon':
20-06:23:13.347 09_23 -EXC- System.Exception: Deconstructor: no output item
  at Assembly-CSharp.QueueSite.UncheckPage (System.Boolean ) [0x000c3] in <2387ce0822d24ebcbe181874328d5d92>:0 
  at Assembly-CSharp.QueueSite.ToggleFunction (System.Int32 ) [0x00057] in <2387ce0822d24ebcbe181874328d5d92>:0 
  at Assembly-CSharp.QueueSite.DetachEmulator (System.Int32& ) [0x000d5] in <2387ce0822d24ebcbe181874328d5d92>:0 
  at Assembly-CSharp.BuilderLoader.InsertBookmark () [0x00151] in <2387ce0822d24ebcbe181874328d5d92>:0 
  at Assembly-CSharp.BuilderLoader.QuoteNetwork (Assembly-CSharp.PartitionResolver , Assembly-CSharp.PluginSite ) [0x0002a] in <2387ce0822d24ebcbe181874328d5d92>:0 
  at Assembly-CSharp.ContextCollection.BuildConnection (Assembly-CSharp.PartitionResolver , Assembly-CSharp.PluginSite , System.Boolean ) [0x00026] in <2387ce0822d24ebcbe181874328d5d92>:0 
  at Assembly-CSharp.PluginSite.QuoteSymbol () [0x0007c] in <2387ce0822d24ebcbe181874328d5d92>:0 
  at Assembly-CSharp.PartitionResolver.HideAddin () [0x00199] in <2387ce0822d24ebcbe181874328d5d92>:0 
  at Assembly-CSharp.FileInvoker.FormatProcess () [0x005de] in <2387ce0822d24ebcbe181874328d5d92>:0 

### POI Name

Communication Array

### Playfield Name

Omicron Moon

### Star Name

Beta

### Mission Name

Communication Array

**Comment by RavienGaming** [comment] 2024-06-20 22:02
That error mentions a deconstructor, which should have nothing to do with the coms array.
I am not sure what the cause, or fix, to this be I'm sorry. I checked both that POI and the deconstructor menu and didn't see any errors.

**Comment by RavienGaming** [comment] 2024-06-21 18:09
Same issue as #152 . Going to close this issue and use #152 as the primary issue thread for this issue. If you have any new updates you can post it there.

**Closed as completed by RavienGaming** 2024-06-21 18:09 UTC
Labels: duplicate
