### ISSUE TITLE
Weapon models not loading from shared data folder

### ISSUE THREAD

**Issue by Arcblade112** [RavienGaming/Reforged-Eden-2#356] opened 2024-10-24 23:33 UTC
### Reforged Eden 2 Build Number

23

### Game mode

Survival, Dedicated Server

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

The weapon models for the MB-14A Sniper Rifle and Combat Knife do not appear in the players hands when on my dedicated server while using a shared data folder. Other weapons may share this issue, but I have not acquired them in-game to test. I loaded into a singleplayer game and the issue does not happen. I also removed the shared data folder URL and loaded into the server without it, and the issue did not happen.

### Playfield Name

Akua

### Playfield Class

Temperate Starter

### Star Name

Alpha

### Star Class

GStartingSystem

### Game Seed

1011345

**Comment by RavienGaming** [comment] 2024-10-25 00:06
Most likely a duplicate of #8  see there for a possible fix for your issue.

**Closed as completed by RavienGaming** 2024-10-25 00:06 UTC
Labels: duplicate
