### ISSUE TITLE
Missing terrain inside Talon village on Arid Mesa planet

### ISSUE THREAD

**Issue by suntrip76** [RavienGaming/Reforged-Eden-2#279] opened 2024-08-22 20:26 UTC
### Reforged Eden 2 Build Number

B20

### Game mode

Survival, Single Player

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

Near the blacksmith and trapper the terrain looks funny making some furniture etc. float in the air.

![billede](https://github.com/user-attachments/assets/d96c53d2-208e-4510-9122-d9af560f3020)

### Playfield Class

Arid Mesa

### Star Name

Elreles

### Star Class

F

### Game Seed

World 489834 - Playfield 154306

**Comment by suntrip76** [comment] 2024-08-22 20:27
Forgot the POI name: R2BA_TalonVillageDesert

**Comment by VermillionX** [comment] 2024-08-23 00:21
Looks like the POI isn't merging with the terrain around it. Will investigate.

**Comment by RavienGaming** [comment] 2024-08-23 00:26
This can occasionally happen even if it's set to flatten terrain if it's near a lot of other POIs and hilly terrain, Not saying that's the cause here but it does happen.

**Comment by suntrip76** [comment] 2024-08-23 04:55
To be fair it's the first one I've seen out of a lot of Talon desert villages during RE2 beta, but also the first time I'm on an Arid desert planet.

Let me know if you want a copy of my savegame, I can upload it to my Dropbox or Wetransfer.

**Comment by VermillionX** [comment] 2024-09-01 13:10
Fixed in next update.
It's an ugly fix, but it'll solve the problem.

**Closed as completed** 2024-09-04 23:33 UTC
Labels: fixed
