### ISSUE TITLE
Unable to complete Black cult depot POI due to shield

### ISSUE THREAD

**Issue by Pyra731** [RavienGaming/Reforged-Eden-2#342] opened 2024-10-09 16:19 UTC
### Reforged Eden 2 Build Number

22

### Game mode

Single Player

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

To clear the POI, you need to switch four levers to "overload the three cores" when the four levers are switched, the cores do not self destruct due to the shield generator preventing damage to them. I Loaded a previous save and went creative, turned off the shield generator manually through the Control panel and switched all four levers and the cores detonated.

### POI Name

Black Cult Depot

**Comment by Pyra731** [comment] 2024-10-09 16:37
In the same POI, in the room with the shield generator, there is a lever on the wall on the lower level on the right hand side from where you walk in with a projection around it saying "eye of the prophet", it's Tx signal is "LevCorrTurrSig" but there doesn't appear to be anything that it controls.

**Comment by Pyra731** [comment] 2024-10-09 18:00
The same issue happens with the "Black Cult Temple of rebirth" POI

**Comment by RavienGaming** [comment] 2024-10-09 19:12
Duplicate of #275

**Closed as completed by RavienGaming** 2024-10-09 19:12 UTC
Labels: duplicate
