### ISSUE TITLE
NOT DUPLICATE PLEASE REOPEN core switches do not work on dedicated server survival - POI Black Cult Temple of Rebirth

### ISSUE THREAD

**Issue by RedScourge** [RavienGaming/Reforged-Eden-2#392] opened 2024-11-28 13:05 UTC
### Reforged Eden 2 Build Number

24

### Game mode

Dedicated Server

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

Zirax POI called Black Cult Temple of Rebirth has 2 cores and 2 core switches, they send a signals LevCoreBoom1 and LevCoreBoom2, together they send a signal called CoreBoom, but it does not appear that the CoreBoom signal actually does anything, as the cores do not blow up. They seem to be surrounded by concrete armored blocks and glass blocks, there's no explosive blocks nearby or anything.

### POI Name

Black Cult Temple of Rebirth

### Playfield Class

Alien Planet

### Star Class

M

### Game Seed

69420

**Comment by RedScourge** [comment] 2024-11-28 13:06
Players on the server complained about it, I checked it out in god mode, I tried flipping the switches, no luck. I tried regenerating the POI then flipping the switches, no luck.

**Comment by RavienGaming** [comment] 2024-12-01 07:19
Duplicate of #275

**Closed as completed by RavienGaming** 2024-12-01 07:19 UTC
Labels: duplicate

**Comment by RedScourge** [comment] 2025-01-02 02:46
This is NOT a duplicate of the other bug, I took the shields down and these two core switches still fail to blow the cores. POI is indeed broken.

**Comment by RavienGaming** [comment] 2025-01-02 04:25
> This is NOT a duplicate of the other bug, I took the shields down and these two core switches still fail to blow the cores. POI is indeed broken.

I updated the POI as of one of the recent updates and verified that the explosive blocks were set correctly and destroyed the core.
If you took down the shield to 0% and it still did not destroy the core then that would be a game bug. Unfortunately signal logic bugs out a lot on dedicated servers.
