### ISSUE TITLE
Broken Abandoned Depot POI (R2BA_AbandonedDepot): full of Hydroponics Bays and Rocket Thrusters, switch to blast doors does not exist

### ISSUE THREAD

**Issue by nafreiu** [RavienGaming/Reforged-Eden-2#353] opened 2024-10-22 12:15 UTC
### Reforged Eden 2 Build Number

21

### Game mode

Dedicated Server

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

POI is full with Hydroponics Bays - Grain (ID:3070/Eden_HydroponicsGrain) and Fruit (ID:3072/Eden_HydroponicsFruit)  as well as Rocket Thrusters (ID:2987/ThrusterMSJunk2x2) .
It's as if certain blocks in POI have been replaced with these blocks - the bays and rocket thrusters are scattered all over the place.

One rocket thruster in particular has been swapped with the switch to the blast doors in the lower level, making it impossible to proceed and complete the POI.

![AnvilS9_2024-10-22_15-10-24](https://github.com/user-attachments/assets/19ca6a6c-6c59-47f0-bb7c-81f36279d401)
![AnvilS9_2024-10-22_15-09-44](https://github.com/user-attachments/assets/a975fbcf-05db-4468-84f0-7c3b81cf8e8d)
![AnvilS9_2024-10-22_15-09-25](https://github.com/user-attachments/assets/e5c7e195-6a7f-4373-998d-597000f3fd2c)
![AnvilS9_2024-10-22_15-10-04](https://github.com/user-attachments/assets/35094797-b258-4064-8e0b-01777dbc75ca)

### POI Name

Abandoned Depot [[Abandoned]]  | R2BA_AbandonedDepot

### Playfield Name

Alpha II

### Playfield Class

Desert

### Star Name

Alpha

### Star Class

GStartingSystem

### Mission Name

-

### Mission Objective

-

### Game Seed

-

**Comment by RavienGaming** [comment] 2024-10-22 18:11
Duplicate of #10

**Closed as completed by RavienGaming** 2024-10-22 18:11 UTC
Labels: duplicate
