### ISSUE TITLE
Space Mining Site mining of pentaxid crystals requires salvage mode, message says drill mode

### ISSUE THREAD

**Issue by Ente2k** [RavienGaming/Reforged-Eden-2#329] opened 2024-09-28 12:49 UTC
### Reforged Eden 2 Build Number

21

### Game mode

Survival, Dedicated Server

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

Trying to mine the pentaxid crystals at the center, as the quest demands, with the drill mode of the multi turret says "you cannot drill this, please switch to the right drilling mode", which is sorta weird since the you are already in the only drilling mode the thing has. Should maybe tell you to switch to salvage mode instead.
(Mining Site Class 1)

### Playfield Name

EdenSpace_POI_MiningT1_2

**Comment by RavienGaming** [comment] 2024-09-28 17:52
Duplicate of #22 

You can mine them with the drill mode of any other ship or handheld drill. So weird that for tool turrets specifically it only works in salvage mode but I assume you don't get the resources from them.

**Closed as completed by RavienGaming** 2024-09-28 17:52 UTC
Labels: duplicate
