### ISSUE TITLE
Co Op Thruster/Weapon/Shooting Soundbugs

### ISSUE THREAD

**Issue by TerrorDragon** [RavienGaming/Reforged-Eden-2#399] opened 2024-12-08 02:20 UTC
### Reforged Eden 2 Build Number

1.11.10 4546

### Game mode

Co-op

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

Hi I have come across a very annoying problem with a friend in the local Co Op.
We are playing RE2 as a scenario and as soon as a CV with any of the new engines is spawned by the factory, the engines start roaring IMMEDIATELY from any distance. I have also moved up to 3 km away from the ship, but when my buddy is standing next to the ship I can still hear the ship sounds clearly on the other side of the planet. Please fix this bug and I don't want a rocket launch on my headset... Also I can hear from any distance when my buddy shoots with a ground weapon or he reloads his weapon etc etc

**Comment by RavienGaming** [comment] 2024-12-08 02:47
Duplicate of #7

**Closed as completed by RavienGaming** 2024-12-08 02:47 UTC
Labels: duplicate
