### ISSUE TITLE
Tech Tree item description 

### ISSUE THREAD

**Issue by Macko13** [RavienGaming/Reforged-Eden-2#100] opened 2024-06-08 18:48 UTC
### Reforged Eden 2 Build Number

build 10

### Game mode

Single Player

### Tested in vanilla

Issue does not happen in vanilla

### Description of issue

Certain items in the Tech tree do not show fully in the description part. So far it is always top part of the description is cut and not visible. My resolution is 3440 x 1440 problem is the resolution, if I lower it then description is visible.

 
![20240608120307_1](https://github.com/RavienGaming/Reforged-Eden-2/assets/172141389/4a660342-76ee-4eeb-887d-8f1efdec0129)

**Comment by RavienGaming** [comment] 2024-08-20 22:23
Duplicate of #198

**Closed as completed by RavienGaming** 2024-08-20 22:23 UTC
Labels: duplicate
