### ISSUE TITLE
Talon Trader on Plantation POI not working

### ISSUE THREAD

**Issue by Ente2k** [RavienGaming/Reforged-Eden-2#200] opened 2024-07-08 20:02 UTC
### Reforged Eden 2 Build Number

15

### Game mode

Dedicated Server

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

Cannot talk to the trader on the Plantation POI. Just doesn't show up the option to initate dialogue.

### POI Name

BA_TalonPlantation2

### Playfield Class

Strange Temperate

**Comment by VermillionX** [comment] 2024-07-09 00:23
There's a plantation POI? Is it a vanilla one?

**Comment by Ente2k** [comment] 2024-07-09 06:04
Well the POI name BA_TalonPlantation2 does imply that it might be a vanilla POI. (Not totally sure about the naming schemes)

**Comment by RavienGaming** [comment] 2024-07-09 06:36
Thanks! Know what the issue is, will work on getting this fixed. The R2 Talon POIs are sharing group names with the vanilla POIs so they are both spawning.

**Comment by RavienGaming** [comment] 2024-07-17 00:14
Should be fixed in the next update.

**Closed as completed** 2024-07-18 00:32 UTC
Labels: fixed
