### ISSUE TITLE
Plasma Cannon Weapon Mod (Ammo) makes cannon non-functional

### ISSUE THREAD

**Issue by StHotPants** [RavienGaming/Reforged-Eden-2#282] opened 2024-08-26 01:35 UTC
### Reforged Eden 2 Build Number

RE2 Beta Build 20

### Game mode

Dedicated Server

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

Added a "red" Weapons Modification to the Plasma Cannon ammunition giving me no blast damage but increased impact damage as shown below:
![image](https://github.com/user-attachments/assets/58578fd0-f0bb-498d-9928-a6e7bbf97b44)

Issue is that now my plasma cannon will not take out/kill anything. Put 10 10MJ Plasma Cell rounds into a static sentry gun from point blank range and did no damage. Shot the same sentry gun 4 times with a LS-75 Laser Rifle and destroyed it. 
Weapon Modification called: Phonon Maser Converter
![image](https://github.com/user-attachments/assets/57daa893-47d9-4c75-8174-04290f88b9b8)

**Comment by VermillionX** [comment] 2024-08-26 05:06
Does it work on troops? If so, then I know what the problem is.

**Comment by VermillionX** [comment] 2024-09-01 13:11
Probably fixed in next update.

**Closed as completed** 2024-09-04 23:33 UTC
Labels: fixed
