### ISSUE TITLE
Zirax and Legacy POI NPC Spawn Problem

### ISSUE THREAD

**Issue by Daimonicon** [RavienGaming/Reforged-Eden-2#320] opened 2024-09-21 19:10 UTC
### Reforged Eden 2 Build Number

Build 22

### Game mode

Single Player

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

The NPC Zirax or Legacy mostly spawn in objects such as shelves, displays, technical equipment, etc. There they can easily shoot at the player, but you can't hit them yourself. This also happened occasionally in RE or even Vanilla, but not to this extent.

### POI Name

Ab. Mine, Outpost, Zirax Drone Base, Black Cult Harvest?, Black Cult Keep, Black Cult Drone Base

**Comment by Daimonicon** [comment] 2024-09-21 20:15
Playfields: YSCU 11349 II (seed 360233) / Ningues / Some Beta's 2+3?

**Comment by RavienGaming** [comment] 2024-09-21 21:27
Duplicate of #302

**Closed as completed by RavienGaming** 2024-09-21 21:27 UTC
Labels: duplicate
